#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

BLUE="\033[1;34m"
GREEN="\033[1;32m"
RED='\033[0;31m'
CLEAR_COLOUR='\033[0m'

echo "pre-push script starting"

# Prevents push if package.json and package-lock.json do not have matching versions
node ./scripts/checkVersions.js
rc=$?
if [[ $rc != 0 ]]; then
    echo "${RED}Pre-push failed on version check - please ensure the package.json and package-lock.json versions are matching${CLEAR_COLOUR}"
    exit $rc
fi

# Prevents push if tests fail
CI=true npm run test
rc=$?
if [[ $rc != 0 ]]; then
    echo "${RED}Pre-push failed on tests - please ensure you fix any failing tests before attempting to push again${CLEAR_COLOUR}"
    exit $rc
fi

echo "${GREEN}pre-push script ran succesfully${CLEAR_COLOUR}"

exit 0
