#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

BLUE="\033[1;34m"
GREEN="\033[1;32m"
RED='\033[0;31m'
CLEAR_COLOUR='\033[0m'

echo "pre-push script starting"

# Prevents push if linter outputs errors or warning
npm run lint -- --max-warnings 0
rc=$?
if [[ $rc != 0 ]]; then
    echo "${RED}Pre-push failed on linter - please ensure you fix any linting errors before attempting to push again${CLEAR_COLOUR}"
    exit $rc
fi

npm run lint:css
rc=$?
if [[ $rc != 0 ]]; then
    echo "${RED}Pre-push failed on CSS linting - please ensure you fix any linting errors before attempting to push again${CLEAR_COLOUR}"
    exit $rc
fi

echo "${GREEN}pre-commit script ran succesfully${CLEAR_COLOUR}"

exit 0
